apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-head-entry
  namespace: {{ default "podtato" .Release.Name }}-helm
  labels:
    {{- include "head" . | indent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "headEntry" . | indent 4 }}
  template:
    metadata:
      labels:
        {{- include "headEntry" . | indent 6 }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      {{- with .Values.head.image }}
      - name: {{ .name }}
        image: "{{ .repository }}:{{ .tag }}"
        imagePullPolicy: {{ .pullPolicy }}
      {{- end }}
        ports:
        - containerPort: 9000
        env:
        - name: PODTATO_PORT
          value: "9000"