apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-head-right-arm
  namespace: {{ default "podtato" .Release.Name }}-helm
  labels:
    {{- include "head" . | indent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "headRightArm" . | indent 4 }}
  template:
    metadata:
      labels:
        {{- include "headRightArm" . | indent 6 }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      {{- with .Values.rightArm.image }}
      - name: {{ .name }}
        image:  {{ .repository }}:{{ .tag }}
        imagePullPolicy: {{ .pullPolicy }}
      {{- end }}
        ports:
          - containerPort: 9000
        env:
          - name: PODTATO_PORT
            value: "9000"