apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-head-hat
  namespace: {{ default "podtato" .Release.Name }}-helm
  labels:
    {{- include "head" . | indent 2 }}
spec:
  selector:
    {{- include "headHat" . | indent 4 }}
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9000
  type: ClusterIP