apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-head-right-leg
  namespace: {{ default "podtato" .Release.Name }}-helm
  labels:
    {{- include "head" . | indent 2 }}
spec:
  selector:
    {{- include "headRightLeg" . | indent 4 }}
  ports:
    - name: http
      port: 9004
      protocol: TCP
      targetPort: 9000
  type: ClusterIP